version: 2

jobs:
  build:
    environment:
      IMAGE_NAME: "harbor.linkorb.com/linkorb/php-docker-base"
    steps:
      - checkout
      - setup_remote_docker:
        docker_layer_caching: true
      - run:
        name: Login into Harbor
        command: |
          echo $DOCKER_USERNAME
          docker login harbor.linkorb.com -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - run:
        name: Build Docker image
        command: docker build -t $IMAGE_NAME:latest .
  publish:
    environment:
      IMAGE_NAME: "harbor.linkorb.com/linkorb/php-docker-base"
    steps:
      - run:
        name: Publish Docker Image to Harbor
        command: docker push $IMAGE_NAME:latest

workflows:
  version: 2
  build-master:
    jobs:
      - build
      - publish
