version: 2
jobs:
  build:
    environment:
      IMAGE_NAME: "harbor.linkorb.com/linkorb/php-docker-base"
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build -t $IMAGE_NAME:latest .
  publish:
    environment:
      IMAGE_NAME: "harbor.linkorb.com/linkorb/php-docker-base"
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - setup_remote_docker
      - run:
          name: Publish Docker Image to Harbor
          command: |
            echo $DOCKER_USERNAME
            docker login harbor.linkorb.com -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
workflows:
  version: 2
  build-master:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - publish:
          requires:
            - build
          filters:
            branches:
              only: master
