name: BuildnContainerForProduction

on:
  workflow_dispatch:
  push:
    branches:
    - master
#  schedule:
#  - cron: 30 1 * * 1

# push to github packages is disabled, almost all of our containers have the new from ghcr.io line.
#jobs:
#  gh-packages:
#    env:
#      REPO_NAME2: $(echo ${{ github.repository }} | awk -F"/" '{print $2}')
#      REPO_NAME: php-docker-base
#      SHA8: $(echo ${GITHUB_SHA} | cut -c1-8)
#      DOCKER_TAG: docker.pkg.github.com/${{ github.repository }}/

#    runs-on: ubuntu-latest

#    steps:
#    - uses: actions/checkout@v2
#    - name: Docker login
#      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login docker.pkg.github.com --username automation@linkorb.com --password-stdin
#    - name: Build the Docker image
#      run: docker build . --tag ${DOCKER_TAG}${REPO_NAME}:latest --file Dockerfile.php7
#    - name: Docker push with latest tag
#      run: docker push ${DOCKER_TAG}${REPO_NAME}:latest
#    - name: Docker retag new image with commit hash
#      run: docker image tag ${DOCKER_TAG}${REPO_NAME}:latest ${DOCKER_TAG}${REPO_NAME}:${{ env.SHA8 }}
#    - name: Docker push with commit hash tag
#      run: docker push ${DOCKER_TAG}${REPO_NAME}:${{ env.SHA8 }}

jobs:
  ghcr:
    runs-on: ubuntu-latest

    steps:
    - name: GitHub Environment Variables Action
      uses: FranzDiebold/github-env-vars-action@v2

    - name: Shallow clone code
      uses: actions/checkout@v2

    - name: GHCR login
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login ghcr.io --username automation@linkorb.com --password-stdin
    
    #php7
    - name: Build the container image
      run: docker build . --tag ghcr.io/linkorb/${{ env.CI_REPOSITORY_NAME }}:latest --file Dockerfile.php7
    - name: Push with latest tag
      run: docker push ghcr.io/linkorb/${{ env.CI_REPOSITORY_NAME }}:latest
    - name: Retag new image with commit hash
      run: docker image tag ghcr.io/linkorb/${{ env.CI_REPOSITORY_NAME }}:latest ghcr.io/linkorb/${{ env.CI_REPOSITORY_NAME }}:$(echo ${GITHUB_SHA} | cut -c1-8)
    - name: Push with commit hash tag
      run: docker push ghcr.io/linkorb/${{ env.CI_REPOSITORY_NAME }}:$(echo ${GITHUB_SHA} | cut -c1-8)
    - name: Retag new image with php7 tag
      run: docker image tag ghcr.io/linkorb/${{ env.CI_REPOSITORY_NAME }}:latest ghcr.io/linkorb/${{ env.CI_REPOSITORY_NAME }}:php7
    - name: Push with commit php7 tag
      run: docker push ghcr.io/linkorb/${{ env.CI_REPOSITORY_NAME }}:php7
      
    #php8
    - name: Build the container image
      run: docker build . --tag ghcr.io/linkorb/${{ env.CI_REPOSITORY_NAME }}:php8 --file Dockerfile.php8
    - name: Push with php8 tag
      run: docker push ghcr.io/linkorb/${{ env.CI_REPOSITORY_NAME }}:php8
    - name: Retag new image with commit hash
      run: docker image tag ghcr.io/linkorb/${{ env.CI_REPOSITORY_NAME }}:php8 ghcr.io/linkorb/${{ env.CI_REPOSITORY_NAME }}:php8-$(echo ${GITHUB_SHA} | cut -c1-8)
    - name: Push with commit hash tag and php8 tag
      run: docker push ghcr.io/linkorb/${{ env.CI_REPOSITORY_NAME }}:php8-$(echo ${GITHUB_SHA} | cut -c1-8)